[package]
name = "network"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonrpsee = { version = "0.26.0", features = ["server", "client", "macros"] }
tokio = "1.48.0"
types = { path = "../types" }
